global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          hotkey: 'replace-me'

remote_write:
  - url: "http://host.docker.internal:8000/prometheus_outbound_proxy"